name = "bg-ko-vocab"
pages_build_output_dir = "./dist"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "bg-ko-vocab"
# Replace with the id printed by: npx wrangler d1 create bg-ko-vocab
database_id = "c3857d82-06b1-45fb-aa92-f89f033ddc5d"
migrations_dir = "migrations"
